package dev.joseph.practice.student_management.student;

import dev.joseph.practice.student_management.school.School;
import dev.joseph.practice.student_management.studentProfile.StudentProfile;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

// Marking this class as an entity so that it can be treated as a table
@Entity
// specifying table name
@Table(name = "studentTable")
public class Student {

    // Marking the instance variable with the id annotation as required by spring, Also telling spring that the instance variable value will be auto generated by spring
    @Id
    @GeneratedValue
    private Integer Id;

    private String name;

    private String email;

    private int age;

    // Every student belong to a school. We have many student in one school, hence the @ManyToOne annotation. The instance of School, carries the id of the School object being passed here. The instance variable is marked with @JoinColumn and this is because we have many students under the school and as such,,,,,,the school is the parent while the student is the child of this association. we also passed a name value and this is to represent the name of the column in the database. Since we are in the student class and student is the child to school, we use @JoinColum
    @ManyToOne
    @JoinColumn(name = "school_id")
    private School school;

    // On this side, we have an instance of StudentProfile. Each student has a profile. The studentProfile instance can be found under the student details and as such the student is the parent of this association while the studentProfile is the child of this association. Since we are in the student class and the student is the parent while the studentProfile is the child, hence we have mappedBy in the OneToOne mapping. The value passed to mappedBy is the field name of parent instance in the child class
    @OneToOne(mappedBy = "student")
    private StudentProfile studentProfile;

    public Student() {
    }

    public Student(String name, String email, int age){
        this.name = name;
        this.email = email;
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public School getSchool() {
        return school;
    }

    public void setSchool(School school) {
        this.school = school;
    }
    public StudentProfile getStudentProfile() {
        return studentProfile;
    }

    public void setStudentProfile(StudentProfile studentProfile) {
        this.studentProfile = studentProfile;
    }



    public int getId() {
        return Id;
    }



    public void setId(int id) {
        Id = id;
    }

    
}
